"""initial platform schema

Baseline migration for Phase 2. Creates the entire operational schema (event
store, tokens/wallets, market/features, signals, strategies/models,
positions/trades, portfolio series, research/opportunities, and the operational
tables). It builds directly from ``Base.metadata`` so the migration can never
drift from the ORM models it mirrors. Subsequent changes use autogenerated
incremental migrations on top of this baseline.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-20
"""

from __future__ import annotations

from alembic import op

# Importing the models package populates Base.metadata with every table.
import hades.shared_kernel.persistence.models  # noqa: F401
from hades.shared_kernel.persistence.database import Base

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
